email: email@domain.com
password: yourpassword
openaiApiKey: ''
disableAntiLock: false
remote: false
lessthanTenApplicants: false
newestPostingsFirst: false
experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false
jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: false
date:
  all time: true
  month: false
  week: false
  24 hours: false
positions:
- engineer
locations:
- united states
residentStatus: false
distance: 100
outputFileDirectory: ~/Documents/EasyApplyBot/
companyBlacklist: []
titleBlacklist: []
posterBlacklist: []
uploads:
  resume: /home/user/简历.pdf
  coverLetter: /home/user/简历.pdf
  photo: ''
checkboxes:
  driversLicence: true
  requireVisa: false
  legallyAuthorized: false
  certifiedProfessional: true
  urgentFill: true
  commute: true
  remote: true
  drugTest: true
  assessment: true
  securityClearance: false
  degreeCompleted:
  - High School Diploma
  - Bachelor's Degree
  backgroundCheck: true
universityGpa: 4.0
salaryMinimum: 65000
languages:
  english: Native or bilingual
  chinese: Native or bilingual
noticePeriod: 2
experience:
  default: 0
  Accounting/Auditing: 0
  Administrative: 0
  Advertising: 0
  Analyst: 0
  Art/Creative: 0
  Business Development: 0
  Consulting: 0
  Customer Service: 0
  Distribution Design: 0
  Education: 0
  Engineering: 0
  Finance: 0
  General Business: 0
  Health Care Provider: 0
  Human Resources: 0
  Information Technology: 0
  Legal: 0
  Management: 0
  Manufacturing: 0
  Marketing: 0
  Public Relations: 0
  Purchasing: 0
  Product Management: 0
  Project Management: 0
  Production: 0
  Quality Assurance: 0
  Research: 0
  Sales: 0
  Science: 0
  Strategy/Planning: 0
  Supply Chain: 0
  Training: 0
  Writing/Editing: 0
  VBA: 0
  PowerBI: 0
  PowerQuery: 0
  Excel: 0
  PowerPoint: 0
  Word: 0
  SQL Server: 0
  Communication: 0
  Financial markets: 0
  Business: 0
  Financial services: 0
  Team leadership: 0
  Cash flow: 0
  Hedging: 0
  Treasury services: 0
  Microsoft Power BI: 0
  Accounting: 0
  Auditing: 0
  Financial modeling: 0
  Budgeting & forecasting: 0
  FP&A: 0
  PQE: 0
  Training & Development: 0
  Python: 5
  Java: 5
personalInfo:
  Pronouns: Mr.
  First Name: FirstName
  Last Name: LastName
  Phone Country Code: Canada (+1)
  Mobile Phone Number: '1234567890'
  Street address: 123 Fake Street
  City: Red Deer, Alberta
  State: YourState
  Zip: YourZip/Postal
  Linkedin: https://www.linkedin.com/in/my-linkedin-profile
  Website: https://www.my-website.com
  MessageToManager: Hi, I am interested to join your organization. Please have a look
    at my resume. Thank you.
eeo:
  gender: male
  race: Aisa
  veteran: 'no'
  disability: 'no'
  citizenship: '1'
  clearance: '0'
textResume: /home/user/简历.txt
evaluateJobFit: false
debug: false
customQuestions:
  Would you like to receive emails, text messages, or phone calls about this job and other matchingopportunities?: 'yes'
  Are you legally authorized to work in the United States?: 'yes'
  Do you have a green card and citizenship?*: 'yes'
  If applying from outside our area, are you willing to pay your own relocation expenses?: 'yes'
  ? Are you willing to travel 50% or more as needed for business needs?Are you willing
    to travel 50% or more as needed for business needs?
  : 'yes'
useCloudAI: true
educations:
- school: Lehigh university
  city: Bethlehem
  degree: ' Bachelor of science '
  major: Computer Science
  from_month: September
  from_year: '2019'
  to_month: May
  to_year: '2023'
  current: false
workExperiences:
- title: 'CO-FOUNDER & ENGINEER '
  company: XXX
  city: San Francisco
  description: 'XXXX'
  from_month: December
  from_year: '2022'
  to_month: Month
  to_year: Year
  current: true
- title: APPLICATION ENGINEER
  company: XXXX
  city: San Francisco
  description: "xxxx"
  from_month: August
  from_year: '2022'
  to_month: August
  to_year: '2023'
  current: false
